import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import dotenv from 'dotenv';

const root = process.cwd();
const envLocalPath = path.join(root, '.env.local');
const envPath = path.join(root, '.env');
const mobileEnvPath = path.join(root, 'apps/mobile/.env');

dotenv.config({ path: envPath });
dotenv.config({ path: envLocalPath, override: true });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();
const supabaseAnon = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?.trim();
const apiUrl = process.env.NEXT_PUBLIC_SITE_URL?.trim() || 'http://localhost:3000';
const googleWebClientId = process.env.GOOGLE_OAUTH_WEB_CLIENT_ID?.trim();
const googleIosClientId = process.env.GOOGLE_OAUTH_IOS_CLIENT_ID?.trim();

if (!supabaseUrl || !supabaseAnon) {
  console.error(
    'Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY.\n' +
      'Add them to .env.local (copy from .env.example), then run this script again.'
  );
  process.exit(1);
}

function detectLanIp(): string | null {
  const interfaces = os.networkInterfaces();
  for (const entries of Object.values(interfaces)) {
    for (const entry of entries ?? []) {
      if (entry.family === 'IPv4' && !entry.internal) {
        return entry.address;
      }
    }
  }
  return null;
}

const lanIp = detectLanIp();
const lines = [
  '# Auto-generated by npm run mobile:env — do not edit manually',
  '# Re-run from repo root after changing .env.local',
  '',
  `EXPO_PUBLIC_SUPABASE_URL=${supabaseUrl}`,
  `EXPO_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnon}`,
  `EXPO_PUBLIC_API_URL=${apiUrl.replace(/\/$/, '')}`,
];

if (googleWebClientId) {
  lines.push(`EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=${googleWebClientId}`);
}
if (googleIosClientId) {
  lines.push(`EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID=${googleIosClientId}`);
}

lines.push('', '# iOS Simulator: localhost works (default above).');

if (lanIp) {
  lines.push(`# Physical iPhone on same Wi-Fi: EXPO_PUBLIC_API_URL=http://${lanIp}:3000`);
}

fs.mkdirSync(path.dirname(mobileEnvPath), { recursive: true });
fs.writeFileSync(mobileEnvPath, `${lines.join('\n')}\n`);

console.log(`Wrote ${path.relative(root, mobileEnvPath)}`);
console.log(`  EXPO_PUBLIC_API_URL=${apiUrl.replace(/\/$/, '')}`);
if (lanIp) {
  console.log(`  Physical device tip: set EXPO_PUBLIC_API_URL=http://${lanIp}:3000 in apps/mobile/.env`);
}
